### PR TITLE
minor typos in comments, removed tautology

### PR DESCRIPTION
**Pull request by drandreaskrueger**
(m_spentToday + _value >= m_spentToday) == (_value >= 0) == true  

because

    uint _value

### CODE REVIEW

**Comment by chriseth** [comment]
It is not a tautology, because those are not integers. It is a n arithmetic overflow protection.

**Comment by drandreaskrueger** [comment]
> overflow protection

Yes, at first I had suspected exactly that. 

Then I used [solidity-repl](solidity-repl) to test if this throws an exception perhaps:

    uint a = 2**255
    a * 2

But it doesn't. It results in a

    0

and 

    0 <= any uint

Or where is the flaw in my thinking?

> those are not integers

What do you mean by that?  

Doesn't `uint` mean unsigned integer?

[uint m_spentToday](https://github.com/drandreaskrueger/dapp-bin/blob/master/wallet/wallet.sol#L273)
[uint _value](https://github.com/drandreaskrueger/dapp-bin/blob/master/wallet/wallet.sol#L254)

**Comment by drandreaskrueger** [comment]
Also tested with `+`

[solr example input](https://github.com/drandreaskrueger/solidity-repl/blob/master/README-win64.md#example-input)

**Comment by drandreaskrueger** [comment]
Now I got it. 

The overflow protection is not by throwing any errors, but if `m_spentToday + _value` overflows, then 

    m_spentToday + _value >= m_spentToday

is false. 

Clever.

I suggest a comment in the code, to explain that.

From my pull request then only the typos remain.

**Comment by drandreaskrueger** [comment]
Thx a lot, @chriseth - my patch-1 branch is deleted. Have a great day ;-)

**Pull request merged**
